import {
  FETCH_COMMUNITIES_SUCCESS,
  FETCH_COMMUNITIES_ERROR,
  FETCH_COMMUNITY_SUCCESS,
  FETCH_COMMUNITY_ERROR,
  UPDATE_COMMUNITY_SUCCESS,
  UPDATE_COMMUNITY_ERROR,
  COMMUNITY_IMAGE_UPLOAD_SUCCESS,
  COMMUNITY_IMAGE_UPLOAD_ERROR,
  MEMBER_COMMUNITY_SUCCESS,
  MEMBER_COMMUNITY_ERROR,
  ASSIGN_MOD_SUCCESS,
  ASSIGN_MOD_ERROR,
  ADD_RULE_SUCCESS,
  ADD_RULE_ERROR,
  REMOVE_RULE_SUCCESS,
  REMOVE_RULE_ERROR
} from '../actions/community';

import {
  FETCH_POSTS_SUCCESS,
  FETCH_POSTS_ERROR,
  FETCH_POST_SUCCESS,
  FETCH_POST_ERROR,
  CREATE_POST_SUCCESS,
  CREATE_POST_ERROR,
  DELETE_POST_SUCCESS,
  DELETE_POST_ERROR,
  CREATE_COMMENT_SUCCESS,
  CREATE_COMMENT_ERROR,
  DELETE_COMMENT_SUCCESS,
  DELETE_COMMENT_ERROR,
  VOTE_SUCCESS,
  VOTE_ERROR
} from '../actions/posts';

import {
  LOGIN_ERROR,
  LOGIN_SUCCESS,
  SIGNUP_ERROR,
  SIGNUP_SUCCESS,
  TOKENUPDATE_SUCCESS,
  TOKENUPDATE_ERROR,
  LOGOUT
} from '../actions/auth';

import {
  USER_UPDATE_SUCCESS,
  USER_UPDATE_ERROR,
  IMAGE_UPLOAD_SUCCESS,
  IMAGE_UPLOAD_ERROR,
  USER_DELETE_SUCCESS,
  USER_DELETE_ERROR
} from '../actions/user';

import { hideErrorClearTimeout, showErrorWithTimeout } from '../actions/error';

export default store => next => action => {
  next(action);
  switch (action.type) {
    case FETCH_COMMUNITIES_SUCCESS:
    case FETCH_COMMUNITY_SUCCESS:
    case UPDATE_COMMUNITY_SUCCESS:
    case COMMUNITY_IMAGE_UPLOAD_SUCCESS:
    case MEMBER_COMMUNITY_SUCCESS:
    case ASSIGN_MOD_SUCCESS:
    case ADD_RULE_SUCCESS:
    case REMOVE_RULE_SUCCESS:
    case FETCH_POSTS_SUCCESS:
    case FETCH_POST_SUCCESS:
    case CREATE_POST_SUCCESS:
    case DELETE_POST_SUCCESS:
    case CREATE_COMMENT_SUCCESS:
    case DELETE_COMMENT_SUCCESS:
    case VOTE_SUCCESS:
    case LOGIN_SUCCESS:
    case SIGNUP_SUCCESS:
    case TOKENUPDATE_SUCCESS:
    case USER_UPDATE_SUCCESS:
    case IMAGE_UPLOAD_SUCCESS:
    case USER_DELETE_SUCCESS:
    case LOGOUT:
      if (store.getState().error) store.dispatch(hideErrorClearTimeout());
      break;

    case FETCH_COMMUNITIES_ERROR:
    case FETCH_COMMUNITY_ERROR:
    case UPDATE_COMMUNITY_ERROR:
    case COMMUNITY_IMAGE_UPLOAD_ERROR:
    case MEMBER_COMMUNITY_ERROR:
    case ASSIGN_MOD_ERROR:
    case ADD_RULE_ERROR:
    case REMOVE_RULE_ERROR:
    case FETCH_POSTS_ERROR:
    case FETCH_POST_ERROR:
    case CREATE_POST_ERROR:
    case DELETE_POST_ERROR:
    case CREATE_COMMENT_ERROR:
    case DELETE_COMMENT_ERROR:
    case VOTE_ERROR:
    case LOGIN_ERROR:
    case SIGNUP_ERROR:
    case TOKENUPDATE_ERROR:
    case USER_UPDATE_ERROR:
    case IMAGE_UPLOAD_ERROR:
    case USER_DELETE_ERROR:
      store.dispatch(showErrorWithTimeout(action.error));
      break;

    default:
      break;
  }
};
